### PR TITLE
Fixing Chapters 1-5

### PR DESCRIPTION
**Pull request by imjoseangel**

### CODE REVIEW

**Comment by imjoseangel** [comment]
@sachinkafle could you please confirm this code for the book? 

Regards

**Comment by sachinkafle** [comment]
Yes indeed! Code are perfectly fine and working. Thanks

**Comment by imjoseangel** [comment]
Can you approve the PR? I will continue reviewing the rest of the chapters from tomorrow

**Review by sachinkafle — APPROVED** [review]

**Comment by imjoseangel** [comment]
Thanks @sachinkafle  for approving. Are you able to merge?

**Comment by sachinkafle** [comment]
I will do it soon. Making sure that everything is fine. I was busy
finishing last two chapters lately so, didn't get enough time. Btw your
suggestions are very helpful-- I tend to do mistakes working on large
projects.. so thanks :) hope to do better with your precious suggestions.

**Pull request merged**
